name: Generate Snake

on:
  schedule:
    - cron: "0 */8 * * *"  # Atualiza a cada 8 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "dist/snake.svg"
